#!/usr/bin/python3
def raise_exception_msg(message=""):
    for i in range(x):
        print(i)
